version: '3.8'

services:
  app:
    build: .
    container_name: pacoca_app
    environment:
      SKIP_COMPOSER: 1
      WEBROOT: /var/www/html/public
      PHP_ERRORS_STDERR: 1
      RUN_SCRIPTS: 1
      REAL_IP_HEADER: 1
      LOG_CHANNEL: stderr
      COMPOSER_ALLOW_SUPERUSER: 1
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
