version: '3.3'
services:
  docker:
    build: ./
    ports:
      - 9002:80
    volumes:
      - ./:/usr/share/nginx/html
    restart: always
    networks:
      - docker

  db:
    image: mysql
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: pacoca
      MYSQL_DATABASE: pacoca
      MYSQL_USER: pacoca
      MYSQL_PASSWORD: pacoca
    networks:
      - docker

networks:
  docker:
    driver: bridge
